name: Python CI 

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-lastest

        steps:
            - name: Checkout code
                uses: actions/checkout@4
            
        steps:
            - nmae: Setup Python
                uses: actions/setup-python@5
                with:
                    python-version: "3.11"
                    
            - name: Install Packages
                run: |
                    pip install -r requirements.txt
            
            - name: Run Test
                run: |
                    pytest
                    



